Add semantic-release
osl-incubator/pyreaddbc pull request #2
Opened 2022-09-17 00:10 UTC by esloch

2022-09-19 14:00 UTC, xmnlab commented
let's have a meeting tomorrow so we can do the review together pls
could you send me an invitation for that pls? thanks

2022-09-20 13:38 UTC, xmnlab requested changes
just added 2 comments here. other than that, LGTM!

2022-09-20 13:38 UTC, xmnlab commented on .github/workflows/release.yaml
> +  build:
keep release job name

2022-09-20 13:38 UTC, xmnlab commented on .github/workflows/release.yaml
> +    - uses: actions/checkout@v2
keep the previous version for the checkout step

2022-09-20 21:06 UTC, esloch commented on .github/workflows/release.yaml
> +  build:
I copied from this [job-name](https://github.com/osl-incubator/poc-semantic-release/blob/main/.github/workflows/release.yaml)

2022-09-20 21:10 UTC, merged